spring:
  cloud:
    gcp:
      project-id: '{cipher}AQBN8/adLk5alYM7h8d6nXBeV40Yaqt3XR40/zcoQCteLmggejR6qcm4VTVGl9Su4OVRbN7By+gyJ6ZeI5HbjGmmxDppiOZ9EfvohCv3fnwIxMkYhFp5YHQ7v3qA3n3nkadbaL5jFCL9W0x2reD42bpjub5mEcNC4J2+WXKPOIkFR73orQJH1c6GyqxQHw8B2U4Gk1uo1kRV2S5VQAWQUwTVSoh4wGyNWdnf+HQyLov7fheJfM0CrVBL+KiDrxMxeCUtoqPdgZdjxAgJqKg6AWtOtKMhrKJxDJa8oai6YuQjCuibApihiBGFr9swQyJ3h105ZrwPJfW4c6AhkPZDuJRK7bzuutO0uZfU7cxxOsXCQ6a3ACFTJaVefsycBHm9P8jAX3XxbkAdDA1P+ioLIfM3'
    bus:
      enabled: true

security:
  oauth2:
    client:
      clientId: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
      clientSecret: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
    resource:
      token-info-uri: http://oauth-server/oauth/check_token
 
mail:
  registration-confirm:
    from: calendario.online.2020@gmail.com
    subject: Confirm Your Calendario Account
    templateName: registration-confirm
    url: http://172.16.8.177:4200/#/app/password/
  registration-success:
    from: calendario.online.2020@gmail.com
    subject: Calendario Account Active
    templateName: registration-success
  event-notification:
    from: calendario.online.2020@gmail.com
    subject: Meeting Scheduled Successfully
    templateName: event-notification
url:
  oauth_server_save_password: http://oauth-server/savePassword
time:
  # 24h = 86400000 Milliseconds
  expiration-activeaccount: 86400000ms
  # 1h = 3600000 Milliseconds
  expiration-resetpassword: 3600000ms
      
message:
  registration-success: Please click on the link, that has been sent to your email account to verify your email and continue the registration process.
  registration-failed: Registration failed.
  registration-confirm-success: Your profile has been activated successfully. Password also changed.
  registration-confirm-failed: Unable to active account.
  email-exist: Email already exist.
  valid-token: Token is valid.
  invalid-token: Invalid token.
  invalid-access-token: Invalid access token.
  access-denied: User is not authorized to access the requested resource.
  slot-create-success: Slots created successfully.
  slot-create-failed: Unable to create slots.
  event-create-success: Event created successfully.
  event-create-failed: Unable to create event.

management:
  endpoints:
    web:
      exposure:
        include: "*"
      