spring:
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: message_service
        instance-connection-name: '{cipher}AQBbJqPytEeG0/pj8Bcb2DwNgP0UC8bEoVz3GYGG5HIV9ls7zAmjB4d5a8nnd0b9A+VWoranGHdBC8gS1dK6K/Pn6ftdYrUjVroKtHyeHjrHwiuitDSUT2R/BGAf0F+5YdU6I2s7R8+fhdQZv2cxEXKS7wuI7Dn/FNlUBAh2S9D+cu0sEHe5pHU6gKw3V6/QOVwAQP7Kl+yWGKZefQUejjqWTw19yqE59wHUWg2s1MD8jED6GDLPPX18/MM6JXwy+ua/dtW669U8sD2m6fB27rySJQ9sXCHLWrAo+BHkWNZqvoegada85nNeJXo9TW5wSmtStO/UANXTKGXX8VPc3oeMKkeABTFeeRZgbMApjU5QMH3TJrK8fCh/crqtptMCCfI8Wdb+Y5A/7meXICMKnrnjMzNk2JtAJnOJx6k9E4+uUw=='
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: calendario_vhost
    username: '{cipher}AQAE54S8OasZaz0/tDMT3hkBeILRc3TXp7S/ysdc93sevcx+bjJfVkfD0DRpBjM9z5z4CpXK7/jE4HkEwL1zTTF506oqHGliXtlx/lwcyRSQv5Y4R7tCXfOyEE5bIZgiaNenMzNH+T7Wv3EYr1lJr0GVoqh7frSxj4oHomrH4AZbwE7N4uGrbzjDuPk6+vkXCt5fy7ahq94DTmALmMl02ljIlWDcLLot3sIN3Vp+Tr1dUKvCXvoXWlnBYLii1zaizosGyfgErV5OpToVNBQgnOnW/Y+JNtR4jrCbaLN6neCJ09eien3woqfla7N224+0mDJ1D/ftHyC3+InH5tvZqSQ/veSDtKxYHKzat27e9rv0YkJiXKHzgWdqZ05S+eXr0zw='
    password: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
  zipkin:
    base-url: 'http://zipkin'
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:postgresql://google/message_service?cloudSqlInstance=${spring.cloud.gcp.sql.instance-connection-name}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
    password: '{cipher}AQAZQkOBaKZm3WWO2PD6jkC/pFPnzJMNc3LoBQvoCfytVy3+8Pq7T6C+IGO5PEZTBqu+SReNQO5D40IIfJEbMWPbWnussdRoJiNib6ftthIzBk9P72B1J98EWmQtT9Kxnr8qUo5NCJw5FXjFjqFBtsz9uHayK7W4pSbvcjvrFK1dqZcLBuVvvj0F7RLD8m0/RE3CgXmelGODAG9MoheTQTASc26JXQViHLKqdR5IWpg2CRLgXzGLNo9YlFyJzEKYPt4P5avAaGMRW23fP8fsi6SaKar48QZv6QO5EWgZil1E7XikKyPii3aO75AWYzNG8jThDPJINTstiqDO1JveST7vEyC359MHj8E6Dlydf/+upFFfKLOXRHspHsaNyJ7Oc8U='
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
          generate_statistics: true
          default_schema: public
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            batch_size: 25
            time_zone: UTC
            lob:
              non_contextual_creation: true
          
credential:
  eureka:
    username: '{cipher}AQCc3nzLjcguTtqIIeSevZZR7JdGG/4jq6+wdaAyVvmsC3La91sPujH4AZ06V91TLrbHmM6ef+mZGXhhSrQoI9IbvkLmggydSPPoMQnIYJe7DUQPpyavoD7xszBuAroPRHtVRnd1UD5dPmmUb9jH4zuK31RUDIBVRZ0+rZOQc4YIt21oHUrFZTSip7jwLmWRqfrlpbYa/4MLI4RkuCvvo3g17Nt2IdQWJVn+ou8XUPB71dOmuqPF35AjCCJgm629h1xrZcFTY9frAAeVwM7FAUpn99ajCVqhNUtWJeIVwG3tuNkCjLeHJp90pjykrt81CquHH0fF3/1fVkU2DgelHfMu+wxevkUSSuHA86UFaQ3hWxbgN37e4+5pV1dQhjkAK+s='
    password: '{cipher}AQCc3nzLjcguTtqIIeSevZZR7JdGG/4jq6+wdaAyVvmsC3La91sPujH4AZ06V91TLrbHmM6ef+mZGXhhSrQoI9IbvkLmggydSPPoMQnIYJe7DUQPpyavoD7xszBuAroPRHtVRnd1UD5dPmmUb9jH4zuK31RUDIBVRZ0+rZOQc4YIt21oHUrFZTSip7jwLmWRqfrlpbYa/4MLI4RkuCvvo3g17Nt2IdQWJVn+ou8XUPB71dOmuqPF35AjCCJgm629h1xrZcFTY9frAAeVwM7FAUpn99ajCVqhNUtWJeIVwG3tuNkCjLeHJp90pjykrt81CquHH0fF3/1fVkU2DgelHfMu+wxevkUSSuHA86UFaQ3hWxbgN37e4+5pV1dQhjkAK+s='

eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://${credential.eureka.username}:${credential.eureka.password}@eureka-server/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000

ribbon: 
  ConnectTimeout: 15000
  ReadTimeout: 35000
  eureka: 
    enabled: true
              