spring:
  cloud:
    gcp:
      project-id: '{cipher}AQBN8/adLk5alYM7h8d6nXBeV40Yaqt3XR40/zcoQCteLmggejR6qcm4VTVGl9Su4OVRbN7By+gyJ6ZeI5HbjGmmxDppiOZ9EfvohCv3fnwIxMkYhFp5YHQ7v3qA3n3nkadbaL5jFCL9W0x2reD42bpjub5mEcNC4J2+WXKPOIkFR73orQJH1c6GyqxQHw8B2U4Gk1uo1kRV2S5VQAWQUwTVSoh4wGyNWdnf+HQyLov7fheJfM0CrVBL+KiDrxMxeCUtoqPdgZdjxAgJqKg6AWtOtKMhrKJxDJa8oai6YuQjCuibApihiBGFr9swQyJ3h105ZrwPJfW4c6AhkPZDuJRK7bzuutO0uZfU7cxxOsXCQ6a3ACFTJaVefsycBHm9P8jAX3XxbkAdDA1P+ioLIfM3'

management:
  endpoints:
    web:
      exposure:
        include: "*"
